# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/shiva

TARGETDEPS += ../libshiva/libshiva.so 
LIBS += -ldl \
        -lshiva 
QMAKE_LIBDIR = ../libshiva 
QMAKE_CXXFLAGS_DEBUG += -DDEBUG 
DEFINES = __SHVSTRING_INCLUDE_UNICODE 
TARGET = ../bin/shiva 
CONFIG = debug \
         warn_on 
TEMPLATE = app 
SOURCES += shiva.cpp 
