# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/sedtemplatesed

INCLUDEPATH += ../../ 
QMAKE_CXXFLAGS_DEBUG += -DDEBUG 
DEFINES = __SHVSTRING_INCLUDE_UNICODE
CONFIG = debug \
          warn_on 
TEMPLATE = app 
SOURCES += dataengine.cpp

LIBS = -L../../../../shivalib/linux/libshiva/ \
  -ldl \
  -lshiva

TARGET = tester

DESTDIR = ../bin

