# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/guitester

HEADERS += modules/shvcontroltester.h
SOURCES += guitester.cpp \
           modules/shvcontroltester.cpp
LIBS += -ldl \
-lshiva
QMAKE_LIBDIR = ../../../../shivalib/linux/libshiva
QMAKE_CXXFLAGS_DEBUG += -DDEBUG
TARGET = ../bin/guitester
CONFIG = debug \
warn_on
TEMPLATE = app
